# 异常处理

## 异常的超类
* Error (错误，如虚拟机挂掉)
* Exception (异常，如程序除0，空指针异常

## 异常分类
* 运行时异常: 如 `NullPointerException`、`ArithmeticException`、`NumberFormatException`、`ClassCastException`
* 编译时异常: 如缺少分号等语法编译错误

## 异常捕获
主要使用关键词 `try`、`catch`、` finally` 实现异常的捕获

<details>
<summary>例题:  空指针异常<br/>
</summary>

``` java
try {
    String str = null;
    System.out.println(" str length = " + str.length());
    fail();
} catch (NullPointerException e) {
    assertTrue(true);
}
```
</details>

<details>
<summary>例题:  数组下标越界异常<br/>
</summary>

``` java
int[] nums = {1, 2, 3, 4, 5};
try {
        int sum = 0;
        for (int i = 0; i <= nums.length; ++i) {
        sum += nums[i];
    }
    System.out.println("sum = " + sum);
    fail();
} catch (IndexOutOfBoundsException e) {
    assertTrue(true);
}
```
</details>

<details>
<summary>例题:  类转换异常<br/>
</summary>

``` java
try {
    String[] strArray = new String[]{"John", "Snow"};
    ArrayList<String> strList = (ArrayList<String>) Arrays.asList(strArray);
    System.out.println("String list: " + strList);
} catch (ClassCastException e) {
    assertTrue(true);
}
```
</details>

<details>
<summary>例题:  算数异常<br/>
</summary>

``` java
try {
    int division = 10 / 0;
    fail();
} catch (ArithmeticException e) {
    assertTrue(true);
}
```
</details>


<details>
<summary>例题:  数字格式化异常<br/>
</summary>

``` java
try {
    int number = Integer.parseInt("123a");
    fail();
} catch (NumberFormatException e) {
    assertTrue(true);
}
```
</details>

注意: 一旦异常触发，异常所在块的代码无法被执行，程序执行流程即将跳转到异常捕获的地方，如果异常未被捕获，程序停止

<details>
<summary>例题:  finally + catch 测试<br/>
</summary>

``` java
int result = 0;
try {
    int number = 10 / 0;
} catch (ArithmeticException e) {
    result++;
}finally {
    result++;
}
assertEquals(2, result);
```
</details>

<details>
<summary>例题:  finally  测试<br/>
</summary>

``` java
int result = 0;
try {
  int number = 10 / 2;
} finally {
  result++;
}
assertEquals(1, result);
```
</details>

<details>
<summary>例题:  finally 返回函数值<br/>
</summary>

``` java
assertEquals(3, func());

public int func() {
    try {
        int num = 10 / 0;
        return 1;
    } catch (ArithmeticException e) {
        return 2;
    }finally {
        return 3;
    }
}
```
</details>

<details>
<summary>例题:  throw及throws 关键词<br/>
</summary>

``` java
@Test
void testThrowException() {
    try {
        int number = parseInt("123a");
        fail();
    } catch (NumberFormatException e) {
        assertTrue(true);
        assertEquals("can't contains non-digits", e.getMessage());
    }
}

public int parseInt(String str) throws NumberFormatException{
    if (!str.matches("\\d+")){
        throw new NumberFormatException("can't contains non-digits");
    }
    return Integer.parseInt(str);
}
```
</details>

<details>
<summary>例题:  自定义异常<br/>
</summary>

``` java
public class CustomExceptionExample extends Exception {

  //  @java.io.Serial
  private static final long serialVersionUID = 234122876006267687L;

  public CustomExceptionExample() {
    super();
  }

  public CustomExceptionExample(String message) {
    super(message);
  }
}

try {
    throw new CustomExceptionExample("custom exception");
} catch (CustomExceptionExample e) {
    assertEquals("custom exception", e.getMessage());
}
```
</details>